DROP DATABASE IF EXISTS learning_db;
CREATE DATABASE learning_db;

DROP DATABASE IF EXISTS course_db;
CREATE DATABASE course_db;

DROP DATABASE IF EXISTS user_db;
CREATE DATABASE user_db;

DROP DATABASE IF EXISTS cart_db;
CREATE DATABASE cart_db;

DROP DATABASE IF EXISTS rating_db;
CREATE DATABASE rating_db;


